openapi: 3.0.0
info:
  title: Baseball scores Plugin
  description: A plugin to allow a user to ask questions about real time baseball scores using ChatGPT.
  version: '1.1.0'
servers:
  - url: http://localhost:3000
    description: Development server
paths:
  /baseball_scores:
    get:
      operationId: getBaseballScores
      summary: Get baseball scores
      parameters:
        - name: "team"
          in: "query"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getBaseballScoresResponse'
components:
  schemas:
    getBaseballScoresResponse:
      type: object
      properties:
        status:
          type: "string"
        data:
          type: "string"
          properties: 
            score:
              type: "string"
        error:
          type: "string"
